# Generated by Django 2.1.4 on 2018-12-09 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0002_squad_name_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='squad_avatars/'),
        ),
        migrations.AddField(
            model_name='squad',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='squad',
            name='info',
            field=models.TextField(default='Дополнительных сведений об отряде не предоставлено.'),
        ),
        migrations.AddField(
            model_name='squad',
            name='rating',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='squad',
            name='name_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
