# Generated by Django 2.1.4 on 2018-12-13 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('squads', '0003_auto_20181209_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquadMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('player', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Состав отряда',
                'verbose_name_plural': 'Составы отрядов',
            },
        ),
        migrations.CreateModel(
            name='SquadRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('player', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка в отряд',
                'verbose_name_plural': 'Заявки в отряды',
            },
        ),
        migrations.AddField(
            model_name='squad',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='squad',
            name='leader',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='squad',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='squad',
            name='avatar',
            field=models.ImageField(null=True, upload_to='squad_avatars/'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='squadrequests',
            name='squad',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='squads.Squad'),
        ),
        migrations.AddField(
            model_name='squadmembers',
            name='squad',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='squads.Squad'),
        ),
    ]
