# Generated by Django 2.1.4 on 2019-07-04 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0004_auto_20190704_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 9, 58, 39, 415105)),
        ),
        migrations.AlterField(
            model_name='squadrequests',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 9, 58, 39, 416103)),
        ),
        migrations.AlterField(
            model_name='squadsectors',
            name='last_pay',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 9, 58, 39, 417104)),
        ),
        migrations.AlterField(
            model_name='squadsectors',
            name='own',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 9, 58, 39, 417104)),
        ),
    ]
