# Generated by Django 2.1.4 on 2018-12-13 10:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0004_auto_20181213_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquadSectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('income', models.IntegerField(default=0)),
                ('own', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Сектор',
                'verbose_name_plural': 'Сектора',
            },
        ),
        migrations.CreateModel(
            name='SquadWear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('for_vip', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Форма',
                'verbose_name_plural': 'Формы',
            },
        ),
        migrations.AddField(
            model_name='squad',
            name='battles_loose',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='squad',
            name='battles_wins',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='squad',
            name='vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='squadmembers',
            name='income',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='squad',
            name='balance',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='squad',
            name='level',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='squad',
            name='rating',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='squadwear',
            name='squad',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='squads.Squad'),
        ),
        migrations.AddField(
            model_name='squadsectors',
            name='squad',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='squads.Squad'),
        ),
    ]
