# Generated by Django 2.1.4 on 2019-07-04 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0005_auto_20190704_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 11, 56, 34, 725789)),
        ),
        migrations.AlterField(
            model_name='squadrequests',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 11, 56, 34, 726775)),
        ),
        migrations.AlterField(
            model_name='squadsectors',
            name='last_pay',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 11, 56, 34, 727774)),
        ),
        migrations.AlterField(
            model_name='squadsectors',
            name='own',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 11, 56, 34, 727774)),
        ),
    ]
