# Generated by Django 2.1.4 on 2018-12-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0005_auto_20181213_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='recruting',
            field=models.BooleanField(default=False),
        ),
    ]
