# Generated by Django 2.1.4 on 2018-12-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0006_squad_recruting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='recruting',
            field=models.BooleanField(default=True),
        ),
    ]
