# Generated by Django 2.1.4 on 2018-12-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0008_auto_20181213_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadwear',
            name='spawn_info',
            field=models.TextField(default='Тут можно указать команды спавна'),
        ),
        migrations.AlterField(
            model_name='squadwear',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
