# Generated by Django 2.1.4 on 2018-12-13 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0009_auto_20181213_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squadmembers',
            name='created',
        ),
        migrations.AlterField(
            model_name='squad',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='squadrequests',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='squadsectors',
            name='squad',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='squads.Squad'),
        ),
    ]
