# Generated by Django 2.1.4 on 2018-12-15 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0011_auto_20181213_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squadwear',
            name='squad',
        ),
        migrations.AddField(
            model_name='squad',
            name='wear',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='squads.SquadWear'),
        ),
        migrations.AddField(
            model_name='squadsectors',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
