# Generated by Django 2.1.4 on 2018-12-17 13:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0012_auto_20181215_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorWars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('war_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('enemy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='squads.Squad')),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='squads.SquadSectors')),
            ],
        ),
    ]
