# Generated by Django 2.1.4 on 2018-12-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0013_sectorwars'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectorwars',
            options={'verbose_name': 'Война за сектор', 'verbose_name_plural': 'Война за секторы'},
        ),
        migrations.AddField(
            model_name='sectorwars',
            name='for_bot_enemy_squad_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sectorwars',
            name='for_bot_sector_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sectorwars',
            name='owner_agreed',
            field=models.BooleanField(default=False),
        ),
    ]
