# Generated by Django 2.1.4 on 2018-12-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0014_auto_20181218_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='squadmembers',
            options={'verbose_name': 'Участник отряда', 'verbose_name_plural': 'Участник отряда'},
        ),
        migrations.AddField(
            model_name='sectorwars',
            name='for_bot_owner_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
