# Generated by Django 2.1.4 on 2018-12-20 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0015_auto_20181219_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectorwars',
            name='enemy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='squads.Squad'),
        ),
        migrations.AlterField(
            model_name='sectorwars',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='squads.SquadSectors'),
        ),
        migrations.AlterField(
            model_name='squadmembers',
            name='player',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='squadmembers',
            name='squad',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='squads.Squad'),
        ),
        migrations.AlterField(
            model_name='squadrequests',
            name='player',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='squadrequests',
            name='squad',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='squads.Squad'),
        ),
    ]
