# Generated by Django 2.1.4 on 2018-12-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0016_auto_20181220_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadsectors',
            name='last_pay',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectorwars',
            name='owner_agreed',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='squad',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='squadrequests',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='squadsectors',
            name='own',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
