# Generated by Django 2.1.4 on 2018-12-21 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0017_auto_20181220_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectorwars',
            name='war_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 13, 33, 6, 513523)),
        ),
        migrations.AlterField(
            model_name='squad',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 13, 33, 6, 513523)),
        ),
        migrations.AlterField(
            model_name='squadrequests',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 13, 33, 6, 513523)),
        ),
        migrations.AlterField(
            model_name='squadsectors',
            name='last_pay',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 13, 33, 6, 513523)),
        ),
        migrations.AlterField(
            model_name='squadsectors',
            name='own',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 13, 33, 6, 513523)),
        ),
    ]
