# Generated by Django 2.1.4 on 2018-12-22 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0018_auto_20181221_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectorwars',
            name='war_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 22, 21, 6, 3, 271182)),
        ),
        migrations.AlterField(
            model_name='squad',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 22, 21, 6, 3, 269188)),
        ),
        migrations.AlterField(
            model_name='squadrequests',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 22, 21, 6, 3, 270185)),
        ),
        migrations.AlterField(
            model_name='squadsectors',
            name='last_pay',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 22, 21, 6, 3, 270185)),
        ),
        migrations.AlterField(
            model_name='squadsectors',
            name='own',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 22, 21, 6, 3, 270185)),
        ),
    ]
