# Generated by Django 2.1.4 on 2018-12-23 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0019_auto_20181222_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectorwars',
            name='owner_denied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sectorwars',
            name='owner_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sectorwars',
            name='war_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 18, 34, 10, 901503)),
        ),
        migrations.AlterField(
            model_name='squad',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 18, 34, 10, 900505)),
        ),
        migrations.AlterField(
            model_name='squadrequests',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 18, 34, 10, 900505)),
        ),
        migrations.AlterField(
            model_name='squadsectors',
            name='last_pay',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 18, 34, 10, 901503)),
        ),
        migrations.AlterField(
            model_name='squadsectors',
            name='own',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 18, 34, 10, 901503)),
        ),
    ]
