# Generated by Django 2.1.4 on 2018-12-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0026_auto_20181223_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectorwars',
            name='war_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
