# Generated by Django 2.1.4 on 2018-12-25 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0029_auto_20181225_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadwear',
            name='image',
            field=models.ImageField(null=True, upload_to='squad_avatars/'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 25, 22, 31, 14, 119238)),
        ),
        migrations.AlterField(
            model_name='squadrequests',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 25, 22, 31, 14, 119238)),
        ),
        migrations.AlterField(
            model_name='squadsectors',
            name='last_pay',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 25, 22, 31, 14, 120236)),
        ),
        migrations.AlterField(
            model_name='squadsectors',
            name='own',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 25, 22, 31, 14, 120236)),
        ),
    ]
