# Generated by Django 2.1.4 on 2019-01-07 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0036_auto_20190105_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectorwars',
            name='owner_denied',
        ),
        migrations.RemoveField(
            model_name='sectorwars',
            name='owner_notify',
        ),
        migrations.AlterField(
            model_name='sectorwars',
            name='owner_agreed',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='squad',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 7, 23, 8, 52, 610610)),
        ),
        migrations.AlterField(
            model_name='squadrequests',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 7, 23, 8, 52, 610610)),
        ),
        migrations.AlterField(
            model_name='squadsectors',
            name='last_pay',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 7, 23, 8, 52, 611608)),
        ),
        migrations.AlterField(
            model_name='squadsectors',
            name='own',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 7, 23, 8, 52, 611608)),
        ),
    ]
