# Generated by Django 2.1.4 on 2019-01-08 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0038_auto_20190107_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadsectors',
            name='in_war',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='squad',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 8, 14, 29, 18, 826151)),
        ),
        migrations.AlterField(
            model_name='squadrequests',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 8, 14, 29, 18, 827147)),
        ),
        migrations.AlterField(
            model_name='squadsectors',
            name='last_pay',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 8, 14, 29, 18, 828145)),
        ),
        migrations.AlterField(
            model_name='squadsectors',
            name='own',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 8, 14, 29, 18, 828145)),
        ),
    ]
