# Generated by Django 2.1.4 on 2019-01-08 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0039_auto_20190108_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectorwars',
            name='for_bot_owner_discord_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='squad',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 8, 16, 5, 0, 847160)),
        ),
        migrations.AlterField(
            model_name='squadrequests',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 8, 16, 5, 0, 848157)),
        ),
        migrations.AlterField(
            model_name='squadsectors',
            name='last_pay',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 8, 16, 5, 0, 848157)),
        ),
        migrations.AlterField(
            model_name='squadsectors',
            name='own',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 8, 16, 5, 0, 848157)),
        ),
    ]
