# Generated by Django 2.1.4 on 2019-02-06 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0041_auto_20190123_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 21, 57, 8, 268453)),
        ),
        migrations.AlterField(
            model_name='squadrequests',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 21, 57, 8, 269451)),
        ),
        migrations.AlterField(
            model_name='squadsectors',
            name='last_pay',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 21, 57, 8, 272442)),
        ),
        migrations.AlterField(
            model_name='squadsectors',
            name='own',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 21, 57, 8, 272442)),
        ),
    ]
