# Generated by Django 2.1.4 on 2019-06-18 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='EventPlayers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spawn_command', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('is_present', models.BooleanField(default=False, verbose_name='Был на событии?')),
                ('event', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('player', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Участник мероприятия',
                'verbose_name_plural': 'Участники мероприятии',
            },
        ),
        migrations.CreateModel(
            name='EventReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_name', models.CharField(default='', max_length=100)),
                ('reward_number', models.IntegerField(default=1)),
                ('reward_image', models.ImageField(default=None, null=True, upload_to='events/')),
                ('spawn_command', models.CharField(blank=True, default='', max_length=100)),
                ('event', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.Event')),
            ],
            options={
                'verbose_name': 'Награда за мероприятие',
                'verbose_name_plural': 'Награды за мероприятия',
            },
        ),
        migrations.CreateModel(
            name='EventTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, null=True)),
                ('image', models.ImageField(default=None, null=True, upload_to='events/')),
                ('info', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Шаблон мероприятия',
                'verbose_name_plural': 'Шаблоны мероприятий',
            },
        ),
        migrations.CreateModel(
            name='PoliceStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obez', models.IntegerField(default=0, verbose_name='Обезврежено')),
                ('victim', models.IntegerField(default=0, verbose_name='Жертвы')),
                ('izyato', models.IntegerField(default=0, verbose_name='Изъято')),
            ],
            options={
                'verbose_name': 'Полицейская стата',
                'verbose_name_plural': 'Полицейская стата',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='template',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.EventTemplates'),
        ),
    ]
