# Generated by Django 2.1.4 on 2019-06-26 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=None, null=True, verbose_name='Дата проведения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='EventPlayers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spawn_command', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Команда спавна')),
                ('is_present', models.BooleanField(default=False, verbose_name='Был на событии?')),
                ('event', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='Участник мероприятия')),
                ('player', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Участник мероприятия',
                'verbose_name_plural': 'Участники мероприятии',
            },
        ),
        migrations.CreateModel(
            name='EventReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_name', models.CharField(default='', max_length=100, verbose_name='Чем награждаем')),
                ('reward_number', models.IntegerField(default=1, verbose_name='Сколько')),
                ('reward_image', models.ImageField(default=None, null=True, upload_to='events/', verbose_name='Картинка')),
                ('spawn_command', models.CharField(blank=True, default='', max_length=100, verbose_name='Команда спавна')),
                ('event', models.ManyToManyField(blank=True, to='events.Event', verbose_name='Награда для мероприятия')),
            ],
            options={
                'verbose_name': 'Награда за мероприятие',
                'verbose_name_plural': 'Награды за мероприятия',
            },
        ),
        migrations.CreateModel(
            name='EventTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, null=True, verbose_name='Название шаблона')),
                ('image', models.ImageField(default=None, null=True, upload_to='events/', verbose_name='Картинка')),
                ('info', models.TextField(default='', verbose_name='Описание мероприятия')),
            ],
            options={
                'verbose_name': 'Шаблон мероприятия',
                'verbose_name_plural': 'Шаблоны мероприятий',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='template',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.EventTemplates', verbose_name='Шаблон для мероприятия'),
        ),
    ]
