# Generated by Django 2.1.4 on 2018-12-21 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20181219_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_name', models.CharField(default='', max_length=100)),
                ('reward_number', models.IntegerField(default=1)),
                ('reward_image', models.ImageField(default=None, null=True, upload_to='events/')),
                ('spawn_command', models.CharField(blank=True, default='', max_length=100)),
                ('event', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.Event')),
            ],
            options={
                'verbose_name': 'Награда за мероприятие',
                'verbose_name_plural': 'Награды за мероприятия',
            },
        ),
        migrations.RemoveField(
            model_name='eventtemplates',
            name='reward',
        ),
    ]
