# Generated by Django 2.1.4 on 2019-02-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_policestat'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventplayers',
            name='is_present',
            field=models.BooleanField(default=False, verbose_name='Был на событии?'),
        ),
    ]
