# Generated by Django 2.1.3 on 2018-12-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('full_text', models.TextField()),
                ('show_on_homepage', models.BooleanField(default=False)),
            ],
        ),
    ]
