# Generated by Django 2.1.4 on 2019-07-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(default=0, max_length=10)),
                ('post_name', models.CharField(max_length=255)),
                ('post_url', models.CharField(default=None, max_length=255, null=True)),
                ('post_image', models.CharField(default=None, max_length=255, null=True)),
                ('post_local', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
