# Generated by Django 2.1.4 on 2018-12-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20181205_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='full_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='tag',
        ),
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='post_id',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
