# Generated by Django 2.1.4 on 2018-12-20 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20181220_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='name',
            new_name='post_name',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='link',
            new_name='post_url',
        ),
        migrations.RemoveField(
            model_name='news',
            name='text',
        ),
    ]
