# Generated by Django 2.1.4 on 2018-12-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20181220_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='post_image',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
