# Generated by Django 2.1.4 on 2018-12-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='post_local',
            field=models.BooleanField(default=False),
        ),
    ]
