# Generated by Django 2.1.4 on 2018-12-22 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20181221_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 22, 21, 6, 3, 266196)),
        ),
    ]
