# Generated by Django 2.1.4 on 2018-12-23 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20181222_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 18, 34, 10, 895519)),
        ),
    ]
