# Generated by Django 2.1.4 on 2018-12-23 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20181223_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 20, 24, 36, 618418)),
        ),
    ]
