# Generated by Django 2.1.4 on 2018-12-23 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20181223_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 20, 39, 34, 895233)),
        ),
    ]
