# Generated by Django 2.1.4 on 2019-08-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_gamechat'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamechat',
            name='logTime',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
