# Generated by Django 2.1.4 on 2019-08-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_gamechat_logtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='KillLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LogTime', models.CharField(blank=True, max_length=20)),
                ('oldLog', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KillStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('killTime', models.CharField(blank=True, max_length=20)),
                ('killerID', models.CharField(blank=True, max_length=20)),
                ('killerNick', models.CharField(blank=True, max_length=100)),
                ('victimID', models.CharField(blank=True, max_length=20)),
                ('victimNick', models.CharField(blank=True, max_length=100)),
                ('killerLocGameCoordX', models.CharField(blank=True, max_length=255)),
                ('killerLocGameCoordY', models.CharField(blank=True, max_length=255)),
                ('killerLocGameCoordZ', models.CharField(blank=True, max_length=255)),
                ('victimLocGameCoordX', models.CharField(blank=True, max_length=255)),
                ('victimLocGameCoordY', models.CharField(blank=True, max_length=255)),
                ('victimLocGameCoordZ', models.CharField(blank=True, max_length=255)),
                ('killerLocCoordX', models.CharField(blank=True, max_length=255)),
                ('killerLocCoordY', models.CharField(blank=True, max_length=255)),
                ('killerLocCoordZ', models.CharField(blank=True, max_length=255)),
                ('victimLocCoordX', models.CharField(blank=True, max_length=255)),
                ('victimLocCoordY', models.CharField(blank=True, max_length=255)),
                ('victimLocCoordZ', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='gamechat',
            name='newLog',
        ),
    ]
