# Generated by Django 2.1.4 on 2019-08-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20190826_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='killstat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='killstat',
            name='isEvent',
            field=models.BooleanField(default=False),
        ),
    ]
