# Generated by Django 2.1.4 on 2019-08-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20190826_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='killstat',
            name='isEvent',
        ),
        migrations.RemoveField(
            model_name='killstat',
            name='killTime',
        ),
        migrations.AddField(
            model_name='killstat',
            name='killerSector',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='killstat',
            name='victimSector',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
