# Generated by Django 2.1.4 on 2019-08-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20190829_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoneName', models.CharField(blank=True, max_length=20, verbose_name='Название зоны')),
                ('zoneX', models.CharField(blank=True, max_length=20, verbose_name='Х')),
                ('zoneY', models.CharField(blank=True, max_length=20, verbose_name='Y')),
                ('repRewardAll', models.IntegerField(default=1, verbose_name='Награда репутация для всех')),
                ('rcRewardAll', models.IntegerField(default=50, verbose_name='Награда RC для всех')),
                ('repRewardTop1', models.IntegerField(default=100, verbose_name='Награда репутация для ТОП1')),
                ('rcRewardTop1', models.IntegerField(default=5000, verbose_name='Награда RC для ТОП1')),
            ],
            options={
                'verbose_name': 'Warzone',
                'verbose_name_plural': 'Warzone',
            },
        ),
    ]
