# Generated by Django 2.1.4 on 2019-09-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_warzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='warzone',
            name='isActive',
            field=models.BooleanField(default=False, verbose_name='Не менять в ручную!'),
        ),
        migrations.AddField(
            model_name='warzone',
            name='zoneImage',
            field=models.ImageField(blank=True, null=True, upload_to='zone_images/', verbose_name='Картинка'),
        ),
    ]
