# Generated by Django 2.1.4 on 2019-09-03 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0009_auto_20190901_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarZonePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerKills', models.IntegerField(default=0)),
                ('playerDeaths', models.IntegerField(default=0)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='warzone',
            name='zoneDescription',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='warzone',
            name='zoneR',
            field=models.CharField(blank=True, max_length=20, verbose_name='Радиус'),
        ),
        migrations.AddField(
            model_name='warzoneplayer',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.WarZone'),
        ),
    ]
