# Generated by Django 2.1.4 on 2018-12-05 16:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0001_initial'),
        ('events', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamuser',
            name='deaths',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='steamuser',
            name='discord_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steamuser',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AddField(
            model_name='steamuser',
            name='kills',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='steamuser',
            name='rating',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=4),
        ),
        migrations.AddField(
            model_name='steamuser',
            name='squad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='squads.Squad'),
        ),
        migrations.AddField(
            model_name='steamuser',
            name='squad_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='steamuser',
            name='vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='steamuser',
            name='wallet',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
