# Generated by Django 2.1.4 on 2019-08-22 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20190724_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 22, 12, 16, 29, 538235), verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='last_buy',
            field=models.DateField(default=datetime.date(2019, 8, 22), verbose_name='Последняя покупка'),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='last_vizit',
            field=models.DateField(default=datetime.date(2019, 8, 22), verbose_name='Последний вход на сайт'),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='last_zp',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 23, 12, 16, 29, 538235), verbose_name='Последняя ЗП'),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='vip_start',
            field=models.DateField(default=datetime.date(2019, 8, 22), verbose_name='Начало действия ВИП'),
        ),
    ]
