# Generated by Django 2.1.4 on 2018-12-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20181205_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='discord_id',
            field=models.CharField(default='testtest#0000', max_length=50, unique=True),
        ),
    ]
