# Generated by Django 2.1.4 on 2018-12-05 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20181205_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamuser',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
