# Generated by Django 2.1.4 on 2018-12-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_steamuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='discord_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
