# Generated by Django 2.1.4 on 2019-07-04 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20190704_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 11, 56, 34, 688784), verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='last_zp',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 5, 11, 56, 34, 688784), verbose_name='Последняя ЗП'),
        ),
    ]
