# Generated by Django 2.1.4 on 2018-12-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20181205_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamuser',
            name='nickname',
            field=models.SlugField(default=123),
            preserve_default=False,
        ),
    ]
