# Generated by Django 2.1.4 on 2019-07-14 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20190704_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 14, 21, 43, 46, 961522), verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='last_buy',
            field=models.DateField(default=datetime.date(2019, 7, 14), verbose_name='Последняя покупка'),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='last_vizit',
            field=models.DateField(default=datetime.date(2019, 7, 14), verbose_name='Последний вход на сайт'),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='last_zp',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 21, 43, 46, 961522), verbose_name='Последняя ЗП'),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='vip_start',
            field=models.DateField(default=datetime.date(2019, 7, 14), verbose_name='Начало действия ВИП'),
        ),
    ]
