# Generated by Django 2.1.4 on 2018-12-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_steamuser_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='nickname',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
