# Generated by Django 2.1.4 on 2018-12-07 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20181206_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamuser',
            name='info',
            field=models.TextField(default='Игрок не указал дополнительных сведений о себе.'),
        ),
        migrations.AddField(
            model_name='steamuser',
            name='is_banned',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='steamuser',
            name='last_zp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='steamuser',
            name='rank',
            field=models.CharField(default='Новичек', max_length=100),
        ),
    ]
