# Generated by Django 2.1.4 on 2018-12-10 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_auto_20181209_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steamuser',
            name='event',
        ),
    ]
