# Generated by Django 2.1.4 on 2018-12-10 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_remove_steamuser_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamuser',
            name='last_vizit',
            field=models.DateTimeField(default=datetime.date(2018, 12, 10)),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='last_zp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 13, 33, 36, 234266)),
        ),
    ]
