# Generated by Django 2.1.4 on 2018-12-10 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_auto_20181210_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='last_zp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 13, 34, 58, 158489)),
        ),
    ]
