# Generated by Django 2.1.4 on 2018-12-10 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_auto_20181210_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='last_vizit',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='last_zp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
