# Generated by Django 2.1.4 on 2018-12-11 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('authentication', '0018_auto_20181210_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steamuser',
            name='last_vizit',
        ),
        migrations.AddField(
            model_name='steamuser',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
