# Generated by Django 2.1.4 on 2018-12-11 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_auto_20181211_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='discord_id',
            field=models.CharField(blank=True, default=None, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='email',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='event',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.Event'),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='squad',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='squads.Squad'),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='steamid',
            field=models.CharField(default=None, max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='wallet',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=8),
        ),
    ]
