# Generated by Django 2.1.4 on 2018-12-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_auto_20181211_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='discord_id',
            field=models.CharField(blank=True, default=None, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='steamid',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
