# Generated by Django 2.1.4 on 2018-12-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_auto_20181211_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='nickname',
            field=models.SlugField(blank=True, default=None, null=True),
        ),
    ]
