# Generated by Django 2.1.4 on 2018-12-13 06:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_auto_20181211_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamuser',
            name='last_vizit',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
