# Generated by Django 2.1.4 on 2018-12-13 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_steamuser_last_vizit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_player_name', models.CharField(max_length=30)),
                ('from_player_name_slug', models.CharField(blank=True, max_length=30)),
                ('from_player_avatar', models.CharField(max_length=255)),
                ('text', models.TextField(default='')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='steamuser',
            name='event',
        ),
        migrations.RemoveField(
            model_name='steamuser',
            name='squad',
        ),
        migrations.AddField(
            model_name='steamuser',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='kills',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='wallet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='privatemessages',
            name='to_player',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
