# Generated by Django 2.1.4 on 2018-12-13 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_auto_20181213_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steamuser',
            name='squad_leader',
        ),
    ]
