# Generated by Django 2.1.4 on 2018-12-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_remove_steamuser_squad_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamuser',
            name='is_squad_leader',
            field=models.BooleanField(default=False),
        ),
    ]
