# Generated by Django 2.1.4 on 2018-12-18 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_auto_20181217_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamuser',
            name='discord_nickname',
            field=models.CharField(blank=True, default=None, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='last_vizit',
            field=models.DateField(default=datetime.date(2018, 12, 18)),
        ),
    ]
