# Generated by Django 2.1.4 on 2018-12-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0029_auto_20181218_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steamuser',
            name='email',
        ),
        migrations.AddField(
            model_name='steamuser',
            name='profile_open',
            field=models.BooleanField(default=True),
        ),
    ]
