# Generated by Django 2.1.4 on 2018-12-19 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0030_auto_20181218_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='last_vizit',
            field=models.DateField(default=datetime.date(2018, 12, 19)),
        ),
    ]
