# Generated by Django 2.1.4 on 2018-12-20 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0033_auto_20181220_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatemessages',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
