# Generated by Django 2.1.4 on 2018-12-21 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0034_auto_20181220_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamuser',
            name='outlaw',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='privatemessages',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 13, 3, 5, 224955)),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 13, 3, 5, 224955), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='last_vizit',
            field=models.DateField(default=datetime.datetime(2018, 12, 21, 13, 3, 5, 224955)),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='last_zp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 20, 13, 3, 5, 224955)),
        ),
    ]
