# Generated by Django 2.1.4 on 2018-12-21 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0035_auto_20181221_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatemessages',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 13, 33, 6, 513523)),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 13, 33, 6, 497899), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='last_vizit',
            field=models.DateField(default=datetime.datetime(2018, 12, 21, 13, 33, 6, 497899)),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='last_zp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 20, 13, 33, 6, 497899)),
        ),
    ]
