# Generated by Django 2.1.4 on 2018-12-23 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0037_auto_20181222_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatemessages',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 18, 34, 10, 894521)),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 18, 34, 10, 892527), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='last_vizit',
            field=models.DateField(default=datetime.datetime(2018, 12, 23, 18, 34, 10, 892527)),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='last_zp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 24, 18, 34, 10, 892527)),
        ),
    ]
