# Generated by Django 2.1.4 on 2018-12-23 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0041_auto_20181223_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatemessages',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 20, 37, 44, 589183)),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 20, 37, 44, 588185), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='last_vizit',
            field=models.DateField(default=datetime.datetime(2018, 12, 23, 20, 37, 44, 588185)),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='last_zp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 24, 20, 37, 44, 588185)),
        ),
    ]
