# Generated by Django 2.1.4 on 2018-12-23 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0044_auto_20181223_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='last_zp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 24, 21, 56, 40, 226212)),
        ),
    ]
