# Generated by Django 2.1.4 on 2018-12-25 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0046_auto_20181225_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 25, 14, 24, 17, 139658), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='last_vizit',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 25, 14, 24, 17, 139658)),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='last_zp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 26, 14, 24, 17, 139658)),
        ),
    ]
