# Generated by Django 2.1.4 on 2018-12-24 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0046_auto_20181224_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='last_zp',
            field=models.DateField(default=datetime.datetime(2018, 12, 25, 23, 36, 51, 303698)),
        ),
    ]
