# Generated by Django 2.1.4 on 2018-12-25 11:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0047_auto_20181225_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 25, 11, 31, 42, 283038, tzinfo=utc), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='last_vizit',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 25, 11, 31, 42, 283038, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='last_zp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 26, 11, 31, 42, 204918, tzinfo=utc)),
        ),
    ]
