# Generated by Django 2.1.4 on 2018-12-25 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0047_auto_20181224_2336'),
        ('authentication', '0051_auto_20181225_1449'),
    ]

    operations = [
    ]
