# Generated by Django 2.1.4 on 2018-12-26 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0056_auto_20181226_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 26, 21, 0, 59, 699516), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='last_zp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 27, 21, 0, 59, 699516)),
        ),
    ]
