# Generated by Django 2.1.4 on 2019-01-08 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0063_auto_20190108_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 8, 16, 5, 0, 842174), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='last_zp',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 9, 16, 5, 0, 842174)),
        ),
    ]
