# Generated by Django 2.1.4 on 2019-07-04 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subitem_color_name', models.CharField(max_length=255)),
                ('subitem_name', models.CharField(max_length=255, null=True)),
                ('subitem_name_slug', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('subitem_name_lower', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('subitem_item_spawn_name', models.CharField(max_length=255, null=True)),
                ('subitem_image', models.ImageField(null=True, upload_to='shop/')),
                ('subitem_active', models.BooleanField(default=True)),
                ('subitem_price', models.IntegerField(default=0)),
                ('subitem_buys', models.IntegerField(default=0)),
                ('subitem_level', models.IntegerField(default=1)),
                ('subitem_discount', models.IntegerField(default=0)),
                ('subitem_for_vip', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Вариант товара',
                'verbose_name_plural': 'Варианты товаров',
            },
        ),
        migrations.RemoveField(
            model_name='items',
            name='set',
        ),
        migrations.AddField(
            model_name='items',
            name='set',
            field=models.ManyToManyField(blank=True, null=True, to='shop.ItemsSets'),
        ),
        migrations.AddField(
            model_name='items',
            name='subitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.SubItem'),
        ),
    ]
