# Generated by Django 2.1.4 on 2018-12-10 13:05

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
        migrations.RenameModel(
            old_name='Item',
            new_name='Items',
        ),
    ]
