# Generated by Django 2.1.4 on 2019-07-24 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsinorder',
            name='item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Items'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='server',
            field=models.IntegerField(default=0, verbose_name='0 - Общий сервер 1- Прватный'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
