# Generated by Django 2.1.4 on 2019-07-04 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190704_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subitem',
            name='subitem_name',
        ),
        migrations.RemoveField(
            model_name='subitem',
            name='subitem_name_lower',
        ),
        migrations.RemoveField(
            model_name='subitem',
            name='subitem_name_slug',
        ),
        migrations.AlterField(
            model_name='items',
            name='subitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.SubItem'),
        ),
    ]
