# Generated by Django 2.1.4 on 2018-12-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20181210_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name_slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
