# Generated by Django 2.1.4 on 2019-07-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190704_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='set',
            field=models.ManyToManyField(blank=True, to='shop.ItemsSets'),
        ),
        migrations.RemoveField(
            model_name='items',
            name='subitem',
        ),
        migrations.AddField(
            model_name='items',
            name='subitem',
            field=models.ManyToManyField(blank=True, to='shop.SubItem'),
        ),
    ]
