# Generated by Django 2.1.4 on 2019-07-04 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190704_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subitem',
            old_name='subitem_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='subitem',
            old_name='subitem_buys',
            new_name='buys',
        ),
        migrations.RenameField(
            model_name='subitem',
            old_name='subitem_color_name',
            new_name='color_name',
        ),
        migrations.RenameField(
            model_name='subitem',
            old_name='subitem_discount',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='subitem',
            old_name='subitem_for_vip',
            new_name='for_vip',
        ),
        migrations.RenameField(
            model_name='subitem',
            old_name='subitem_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='subitem',
            old_name='subitem_item_spawn_name',
            new_name='item_spawn_name',
        ),
        migrations.RenameField(
            model_name='subitem',
            old_name='subitem_level',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='subitem',
            old_name='subitem_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='items',
            name='set',
        ),
        migrations.RemoveField(
            model_name='items',
            name='subitem',
        ),
        migrations.AddField(
            model_name='baskets',
            name='subitem',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.SubItem'),
        ),
        migrations.AddField(
            model_name='favoriteitems',
            name='subitem',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.SubItem'),
        ),
        migrations.AddField(
            model_name='itemsinorder',
            name='subitem',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.SubItem'),
        ),
        migrations.AddField(
            model_name='subitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Items'),
        ),
    ]
