# Generated by Django 2.1.4 on 2019-07-04 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0005_auto_20190704_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='set_images/')),
                ('description', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Часть сета',
                'verbose_name_plural': 'Части сетов',
            },
        ),
        migrations.AlterField(
            model_name='baskets',
            name='item',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Items'),
        ),
        migrations.AlterField(
            model_name='baskets',
            name='number',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='baskets',
            name='player',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemsinorder',
            name='item',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Items'),
        ),
        migrations.AlterField(
            model_name='itemsinorder',
            name='number',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='itemsinorder',
            name='order',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Orders'),
        ),
        migrations.RenameModel(
            old_name='ItemsSets',
            new_name='Set',
        ),
        migrations.AddField(
            model_name='setimage',
            name='set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Set'),
        ),
    ]
