# Generated by Django 2.1.4 on 2019-07-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190704_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='spawn_commands',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
