# Generated by Django 2.1.4 on 2018-12-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20181210_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_spawn_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
