# Generated by Django 2.1.4 on 2019-07-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20190704_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='server',
            field=models.IntegerField(default=0),
        ),
    ]
