# Generated by Django 2.1.4 on 2018-12-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20181212_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baskets',
            name='order',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='info',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='views',
        ),
        migrations.RemoveField(
            model_name='items',
            name='info',
        ),
        migrations.RemoveField(
            model_name='items',
            name='views',
        ),
        migrations.AlterField(
            model_name='baskets',
            name='current_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='baskets',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemsinorder',
            name='current_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemsinorder',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
