# Generated by Django 2.1.4 on 2019-07-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20190717_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
