# Generated by Django 2.1.4 on 2019-07-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_set_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
