# Generated by Django 2.1.4 on 2018-12-13 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20181213_0926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='for_vip',
            new_name='for_squad',
        ),
        migrations.AddField(
            model_name='items',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Categories'),
        ),
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(null=True, upload_to='shop/'),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_spawn_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
