# Generated by Django 2.1.4 on 2018-12-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20181213_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
