# Generated by Django 2.1.4 on 2018-12-16 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0012_auto_20181215_2116'),
        ('shop', '0013_categories_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='for_sector',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='squads.SquadSectors'),
        ),
    ]
