# Generated by Django 2.1.4 on 2018-12-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_categories_for_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_spawn_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
