# Generated by Django 2.1.4 on 2018-12-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20181225_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='spawn_text',
            field=models.TextField(default=''),
        ),
    ]
